## Python and Pandas

### Step 1: Understand the Data

In [2]:
import pandas as pd
#Importing and reading CSV file
df = pd.read_csv('delivery_data_with_restaurants.csv')

In [3]:
#Checking Number of rows and columns 
df.shape

(10000, 12)

In [4]:
#Checking Column names 
df.columns

Index(['order_id', 'order_time', 'delivery_time', 'delivery_duration_min',
       'city', 'state', 'latitude', 'longitude', 'restaurant', 'is_canceled',
       'cancel_reason', 'customer_rating'],
      dtype='str')

In [5]:
#Checking Data types 
df.dtypes

order_id                     str
order_time                   str
delivery_time                str
delivery_duration_min    float64
city                         str
state                        str
latitude                 float64
longitude                float64
restaurant                   str
is_canceled                 bool
cancel_reason                str
customer_rating          float64
dtype: object

In [6]:
#Checking first few records
df.head()

,order_id,order_time,delivery_time,delivery_duration_min,city,state,latitude,longitude,restaurant,is_canceled,cancel_reason,customer_rating
0,e5b99ed3-4bd6-4aed-9583-989823be022d,2025-04-10 13:21:00,2025-04-10 13:58:00,37.0,New York,NY,40.7128,-74.0060,Pasta Place,False,NaN,4.9
1,fd83af05-01fa-4b33-9254-b2708993a58a,2025-01-26 08:45:00,2025-01-26 09:06:00,21.0,Dallas,TX,32.7767,-96.7970,Taco Town,False,NaN,4.8
2,f4ab757f-669e-4b5a-9279-4b88a456fca8,2025-01-20 21:27:00,2025-01-20 22:22:00,55.0,San Jose,CA,37.3382,-121.8863,Burger Haven,False,NaN,4.1
3,8e4247d0-c211-445b-81c0-3d13e9101398,2024-12-12 16:17:00,2024-12-12 16:55:00,38.0,San Diego,CA,32.7157,-117.1611,Seafood Delight,False,NaN,4.7
4,65c2f48f-4a3c-4159-8eaf-22ae6a1fbff2,2025-03-01 14:24:00,2025-03-01 14:47:00,23.0,Philadelphia,PA,39.9526,-75.1652,The Gourmet Kitchen,False,NaN,4.6

In [7]:
#Checking last few records
df.tail()

,order_id,order_time,delivery_time,delivery_duration_min,city,state,latitude,longitude,restaurant,is_canceled,cancel_reason,customer_rating
9995,cb598861-e313-4836-873d-93a788b8150c,2025-04-20 18:18:00,2025-04-20 19:07:00,49.0,Los Angeles,CA,34.0522,-118.2437,Taco Town,False,NaN,3.7
9996,475f4e9d-6288-4d22-8c62-0147faece970,2025-02-06 12:04:00,2025-02-06 13:11:00,67.0,San Antonio,TX,29.4241,-98.4936,Pasta Place,False,NaN,2.8
9997,9e9a46d2-5d11-4be8-9fd1-3640d431a976,2025-01-22 19:12:00,2025-01-22 19:48:00,36.0,San Antonio,TX,29.4241,-98.4936,Burger Haven,False,NaN,5.0
9998,aafe9464-69d4-4449-a6bf-5d392ddf14ab,2024-11-04 12:33:00,2024-11-04 13:52:00,79.0,San Jose,CA,37.3382,-121.8863,Bistro Belle,False,NaN,3.3
9999,def496b0-2729-4274-948f-c3956eeab6e4,2025-03-07 18:28:00,2025-03-07 19:52:00,84.0,Philadelphia,PA,39.9526,-75.1652,Taco Town,False,NaN,2.0

In [8]:
#Basic statistical information
df.describe()

       delivery_duration_min      latitude     longitude  customer_rating
count            8961.000000  10000.000000  10000.000000      8961.000000
mean               49.369490     35.179529    -99.659819         3.916416
std                17.655349      4.260429     16.537018         0.895868
min                20.000000     29.424100   -121.886300         1.000000
25%                36.000000     32.715700   -117.161100         3.500000
50%                47.000000     34.052200    -98.493600         4.100000
75%                59.000000     39.952600    -87.629800         4.600000
max                90.000000     41.878100    -74.006000         5.000000

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               10000 non-null  str
 1   order_time             10000 non-null  str
 2   delivery_time          8961 non-null   str
 3   delivery_duration_min  8961 non-null   float64
 4   city                   10000 non-null  str
 5   state                  10000 non-null  str
 6   latitude               10000 non-null  float64
 7   longitude              10000 non-null  float64
 8   restaurant             10000 non-null  str
 9   is_canceled            10000 non-null  bool
 10  cancel_reason          1039 non-null   str
 11  customer_rating        8961 non-null   float64
dtypes: bool(1), float64(4), str(7)
memory usage: 869.3 KB

### Step 2: Data Cleaning

In [10]:
#Checking missing values 
df.isna().sum()

order_id                    0
order_time                  0
delivery_time            1039
delivery_duration_min    1039
city                        0
state                       0
latitude                    0
longitude                   0
restaurant                  0
is_canceled                 0
cancel_reason            8961
customer_rating          1039
dtype: int64

In [11]:
df[df["delivery_time"].isnull()].head()

,order_id,order_time,delivery_time,delivery_duration_min,city,state,latitude,longitude,restaurant,is_canceled,cancel_reason,customer_rating
11,1dc8e974-ce17-48b2-a8c1-ff59e8a17a92,2025-02-20 15:42:00,NaN,NaN,Los Angeles,CA,34.0522,-118.2437,Bistro Belle,True,Other,NaN
20,7b2bdaf1-c344-4227-91b5-bbbc3fbf7e32,2025-03-04 08:25:00,NaN,NaN,Los Angeles,CA,34.0522,-118.2437,Steakhouse King,True,Payment Issue,NaN
22,0eeeb174-0374-4ecf-8eea-ecc45ca7b371,2025-04-18 12:33:00,NaN,NaN,San Antonio,TX,29.4241,-98.4936,Sushi World,True,Customer Request,NaN
44,51b92505-1a3b-4037-90c6-19fd1d5410f6,2025-03-05 17:59:00,NaN,NaN,Chicago,IL,41.8781,-87.6298,Sushi World,True,Scam,NaN
46,ee91b8e6-ceb0-4893-b351-50dfe8ad5663,2025-03-05 11:26:00,NaN,NaN,Philadelphia,PA,39.9526,-75.1652,Burger Haven,True,Other,NaN

In [12]:
#  delivery_time - 1039 missing,The order was cancelled, so the food was never delivered so,there is no delivery time
# delivery_duration_min - 1039 missing ,Since the order was cancelled, there was no completed delivery.
# cancel_reason — 8961 missing 
# successful orders , is_canceled = False and cancel_reason = NaN
# The order was not cancelled, so there is no cancellation reason
# Replacing missing values of cancel_reason with 'Not Cancelled'
# customer_rating — 1039 missing(is_canceled = True,customer_rating = NaN)
# The order was cancelled, so there was likely no completed customer experience to rate

df["cancel_reason"] = df["cancel_reason"].fillna("Not Cancelled")

In [13]:
# Checking if value is correctly replaced
df.isnull().sum()

order_id                    0
order_time                  0
delivery_time            1039
delivery_duration_min    1039
city                        0
state                       0
latitude                    0
longitude                   0
restaurant                  0
is_canceled                 0
cancel_reason               0
customer_rating          1039
dtype: int64

In [14]:
# Ensuring Null value is correctly replaced 
df.tail()

,order_id,order_time,delivery_time,delivery_duration_min,city,state,latitude,longitude,restaurant,is_canceled,cancel_reason,customer_rating
9995,cb598861-e313-4836-873d-93a788b8150c,2025-04-20 18:18:00,2025-04-20 19:07:00,49.0,Los Angeles,CA,34.0522,-118.2437,Taco Town,False,Not Cancelled,3.7
9996,475f4e9d-6288-4d22-8c62-0147faece970,2025-02-06 12:04:00,2025-02-06 13:11:00,67.0,San Antonio,TX,29.4241,-98.4936,Pasta Place,False,Not Cancelled,2.8
9997,9e9a46d2-5d11-4be8-9fd1-3640d431a976,2025-01-22 19:12:00,2025-01-22 19:48:00,36.0,San Antonio,TX,29.4241,-98.4936,Burger Haven,False,Not Cancelled,5.0
9998,aafe9464-69d4-4449-a6bf-5d392ddf14ab,2024-11-04 12:33:00,2024-11-04 13:52:00,79.0,San Jose,CA,37.3382,-121.8863,Bistro Belle,False,Not Cancelled,3.3
9999,def496b0-2729-4274-948f-c3956eeab6e4,2025-03-07 18:28:00,2025-03-07 19:52:00,84.0,Philadelphia,PA,39.9526,-75.1652,Taco Town,False,Not Cancelled,2.0

In [15]:
# Checking duplicate values
df.duplicated().sum()

np.int64(0)

In [16]:
# Assisgning correct datatype to order_time,delivery_time,delivery_duration_min 
df["order_time"] = pd.to_datetime(df["order_time"])

In [17]:
df["delivery_time"] = pd.to_datetime(df["delivery_time"])

In [18]:
df["delivery_duration_min"] = df["delivery_duration_min"].astype(float)

In [19]:
# Ensuring that the datatype of those column mentioned above is converted
df.dtypes

order_id                            str
order_time               datetime64[us]
delivery_time            datetime64[us]
delivery_duration_min           float64
city                                str
state                               str
latitude                        float64
longitude                       float64
restaurant                          str
is_canceled                        bool
cancel_reason                       str
customer_rating                 float64
dtype: object

### Step 3: Create a New Column

In [20]:
import numpy as np
df["Delivery_Status"] = np.where(
    df["delivery_duration_min"] <= 30,
    "Fast",
    np.where(
        df["delivery_duration_min"] <= 45,
        "Normal",
        "Delayed"
    )
)
df.head()

,order_id,order_time,delivery_time,delivery_duration_min,city,state,latitude,longitude,restaurant,is_canceled,cancel_reason,customer_rating,Delivery_Status
0,e5b99ed3-4bd6-4aed-9583-989823be022d,2025-04-10 13:21:00,2025-04-10 13:58:00,37.0,New York,NY,40.7128,-74.0060,Pasta Place,False,Not Cancelled,4.9,Normal
1,fd83af05-01fa-4b33-9254-b2708993a58a,2025-01-26 08:45:00,2025-01-26 09:06:00,21.0,Dallas,TX,32.7767,-96.7970,Taco Town,False,Not Cancelled,4.8,Fast
2,f4ab757f-669e-4b5a-9279-4b88a456fca8,2025-01-20 21:27:00,2025-01-20 22:22:00,55.0,San Jose,CA,37.3382,-121.8863,Burger Haven,False,Not Cancelled,4.1,Delayed
3,8e4247d0-c211-445b-81c0-3d13e9101398,2024-12-12 16:17:00,2024-12-12 16:55:00,38.0,San Diego,CA,32.7157,-117.1611,Seafood Delight,False,Not Cancelled,4.7,Normal
4,65c2f48f-4a3c-4159-8eaf-22ae6a1fbff2,2025-03-01 14:24:00,2025-03-01 14:47:00,23.0,Philadelphia,PA,39.9526,-75.1652,The Gourmet Kitchen,False,Not Cancelled,4.6,Fast

### Step 4: Perform Basic Analysis

In [21]:
# Total number of orders
total_orders = df["order_id"].count()
print("Total number of orders:", total_orders)

Total number of orders: 10000

In [22]:
# Average delivery time 
average_delivery_time = df["delivery_duration_min"].mean()
print("Average delivery time:", round(average_delivery_time, 2))

Average delivery time: 49.37

In [23]:
# Cancellation percentage
cancellation_percentage = df["is_canceled"].mean() * 100
print("Cancellation Percentage:", round(cancellation_percentage, 2), "%")

Cancellation Percentage: 10.39 %

In [24]:
# Average customer rating
average_rating = df["customer_rating"].mean()
print("Average Customer Rating:", round(average_rating, 2))

Average Customer Rating: 3.92

In [25]:
#  Restaurant with the highest average delivery time
restaurant_avg_delivery = df.groupby("restaurant")["delivery_duration_min"].mean()

restaurant_highest_delivery = restaurant_avg_delivery.idxmax()

print("Restaurant:", restaurant_highest_delivery)
print("Average Delivery Time:", restaurant_avg_delivery.max())

Restaurant: Pasta Place
Average Delivery Time: 49.845474613686534

In [26]:
# Location with the highest number of delayed orders
delayed_orders = df[df["Delivery_Status"] == "Delayed"]
delayed_by_location = delayed_orders.groupby("city").size()
print("Location with highest delayed orders:", delayed_by_location.idxmax())
print("Number of delayed orders:", delayed_by_location.max())

Location with highest delayed orders: San Antonio
Number of delayed orders: 627

In [27]:
# Exporting the cleaned dataset
df.to_csv("cleaned_food_delivery.csv", index=False)